services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esther-web
    user: "node"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3001}:3000"
