/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { SessionRequest_jsonld } from './SessionRequest_jsonld';
/**
 * A Session represents an User's successful login.
 */
export type Session_jsonld = {
    readonly '@context'?: (string | Record<string, any>);
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    /**
     * The User who created this Session.
     */
    user?: string;
    /**
     * An authentication token value generated by the API.
     */
    token?: string;
    /**
     * Some of the headers in the HTTP request that originated this Session.
     */
    request?: SessionRequest_jsonld;
    readonly dateCreated?: string;
    readonly dateUpdated?: string;
};

